data_args:
  path: datasets
  fs: 50
  activities:
  - walk
  position: LH
  dataset: MMgait-nonan

main_args:
  load_data: false

  trim_duration: 5
  checks:
  orient_method:
  include_gravity: true
  gravity_cutoff: 0.1
  new_features:
  filter:
  filter_cutoff: 10.0

  labels:
  - LF_HS
  task: gait_events
  targets: one
  target_position: center

  split_type: loso
  test_hold_out:
  - 107
  validation: false
  val_hold_out:

  - 3
  duration: 4
  stride: 1

  features:
  - acc_x
  - acc_y
  - acc_z
  batch_size: 128

  architecture: cnn-gru
  rotation_layer:
  optimizer: adam
  epochs: 250
  learning_rate: 0.0001
  head: single
  class_weights: true

  metrics:
  - f1
  - accuracy
  - precision
  - recall



