data_args:
  path: datasets
  fs: 50
  activities:
  - walking
  position: Wrist

main_args:
  load_data: false

  cleaner: linear
  include_gravity: false
  gravity_cutoff: 0.5
  new_features:
  - norm_xyz
  - norm_xy
  - elevation
  filter: lowpass
  filter_window: 3
  filter_cutoff: 10.0
  rescaler: standard
  parameters:
  - left_stance
  task: gait_phases
  fft: false

  split_type: loso  # loso, start, end
  test_hold_out: [5, 7, 14]
  validation: false
  val_hold_out: 1

  duration: 4 # seconds
  stride: 1    # seconds

  features: # List(norm_xyz, norm_xy, norm_yz, norm_xz, jerk, low_x, low_y, low_z)
  - acc_x
  - acc_y
  - acc_z
  - norm_xyz
  - norm_xy
  - elevation
  augmentations: # List(rotate, jitter, scale)
  batch_size: 64

  architecture: cnn
  optimizer: adam
  epochs: 250
  learning_rate: 0.001

  metrics:
  - f1
  - accuracy
  - precision
  - recall



