data_args:
  path: datasets
  fs: 50
  activities:
  - walk
  position: LH
  dataset: marea

main_args:
  load_data: false

  cleaner: linear
  checks:
  orient_method:
  include_gravity: true
  gravity_cutoff: 0.1
  new_features:
  filter:
  filter_window: 3
  filter_cutoff: 10.0
  rescaler:

  labels:
  - LF_HS
  task: gait_events
  targets: one
  target_position: center

  trim_duration: 5
  fft: false
  spectrogram: false
  stft_duration: 1.6
  stft_step: 0.1

  split_type: loso    #loso, start, end
  test_hold_out:
  - 3
  validation: false
  val_hold_out: 1

  duration: 4 # seconds
  stride: 1   # seconds

  features: # List(norm_xyz, norm_xy, norm_yz, norm_xz, jerk, low_x, low_y, low_z)
  - acc_x
  - acc_y
  - acc_z
  augmentations: # List(rotate, jitter, scale)
  batch_size: 128

  architecture: cnn-gru
  rotation_layer: rotate_by_axis
  optimizer: adam
  epochs: 250
  learning_rate: 0.0001
  head: single
  class_weights: true

  metrics:
  - f1
  - accuracy
  - precision
  - recall



