sl_params = {
    'cleaner': 'linear',
    'checks': None,
    'orient_method': None,
    'include_gravity': True,
    'gravity_cutoff': 0.1,
    'new_features': None,
    'filter': None,
    'filter_window': 3,
    'filter_cutoff': 10.0,
    'rescaler': None,
    'labels': ['LF_HS'],
    'task': 'gait_events',
    'targets': 'one',
    'target_position': 'center',
    'trim_duration': 5,
    'duration': 4,
    'stride': 1,
    'features': ['acc_x', 'acc_y', 'acc_z'],
    'augmentations': None,
    'fft': False,
    'spectrogram': False,
    'stft_duration': 1.6,
    'stft_step': 0.1,
    'split_type': 'loso',
    'test_hold_out': [3],

    'batch_size': 128,
    'architecture': 'cnn-gru',
    'rotation_layer': 'rotate_by_axis',
    'optimizer': 'adam',
    'epochs': 250,
    'decay_steps': 0,
    'lr_decay': None,
    'learning_rate': 0.0001,
    'head': 'single',
    'class_weights': True,
}

