sl_params = {
    'cleaner': 'linear',
    'include_gravity': False,
    'new_features': ['norm_xyz', 'norm_xz'],
    'filter': 'lowpass',
    'filter_window': 3,
    'filter_cutoff': 10.,
    'rescaler': 'standard',
    'parameters': ['right_stance'],
    'task': 'gait_phases',
    'duration': 4,
    'stride': 1,
    'features': ['acc_x', 'acc_y', 'acc_z', 'norm_xyz', 'norm_xz'],
    'augmentations': None,
    'fft': False,
    'batch_size': 64,
    'architecture': 'cnn',
    'optimizer': 'adam',
    'epochs': 250,
    'decay_steps': 0,
    'lr_decay': None,
    'learning_rate': 0.001
}