data_args:
  path: datasets
  fs: 50
  activities:
  - walk
  position: LH
  dataset: marea-nonan-MMgait
main_args:
  load_data: false

  trim_duration: 5
  checks:
  orient_method:
  include_gravity: true
  gravity_cutoff: 0.1
  new_features:
  filter:
  filter_cutoff: 10.0

  labels:
  - LF_HS
  task: gait_events
  targets: all
  target_position: center
  target_oversampling: 2

  split_type: dataset
  test_hold_out: mmgait
  validation: false
  val_hold_out: mmgait
  duration: 4
  stride: 4

  features:
  - acc_x
  - acc_y
  - acc_z
  xyz: true

  batch_size: 128
  augmentations:
  architecture: cnn-gru
  rotation_layer:
  optimizer: adam
  epochs: 250
  learning_rate: 0.0001
  head: temporal_single
  class_weights: true
  loss: tversky
  metric: accuracy



