data_args:
  path: datasets
  fs: 50
  activities:
  - walk
  position: RH
  dataset: nonan-MMgait

main_args:
  load_data: false

  trim_duration: 5
  checks:
  orient_method:
  include_gravity: true
  gravity_cutoff: 0.1
  new_features:
  filter:
  filter_cutoff: 10.0

  labels:
  - RF_TO
  task: gait_events
  targets: all
  target_position: center
  target_oversampling: 2

  split_type: loso
  test_hold_out:
  - 1001
  - 1022
  - 1010
  - 1013
  validation: true
  val_hold_out:
  - 1018
  - 1014
  - 1002
  - 1025
  duration: 2.56
  stride: 2

  features:
  - acc_x
  - acc_y
  - acc_z
  xyz: false

  augmentations:
  architecture: unet
  rotation_layer:
  optimizer: adam
  epochs: 250
  learning_rate: 0.0001
  head: temporal
  class_weights: true
  loss: bce
  metric: accuracy

  anchor: LH
  target: LF
  batch_method: random
  batch_size: 64
  negative_subject: same
  negative_position: all






